let keyIndex = 0;

const key = (prefix: string) => `${prefix}-${++keyIndex}`;

const slug = (current: string) => ({ _type: "slug", current });

const block = (text: string, style = "normal") => ({
  _type: "block",
  _key: key("block"),
  style,
  markDefs: [],
  children: [{ _type: "span", _key: key("span"), text, marks: [] }],
});

const image = (assetPath: string, alt: string) => ({
  _type: "imageWithAlt",
  _key: key("image"),
  assetPath,
  alt,
});

const ref = (_ref: string) => ({ _type: "reference", _ref });

const internalUrl = (_ref: string) => ({
  _type: "customUrl",
  type: "internal",
  internal: ref(_ref),
});

const link = (name: string, target: string) => ({
  _key: key("nav"),
  _type: "navbarLink",
  name,
  url: internalUrl(target),
});

const button = (text: string, target: string, variant = "default") => ({
  _key: key("button"),
  _type: "button",
  text,
  variant,
  url: internalUrl(target),
});

const gallery = (paths: string[], alt: string) => paths.map((path) => image(path, alt));

const serviceGallery = {
  stalbygg: [
    "/assets/20251210_134006.webp",
    "/assets/20251218_103336.webp",
    "/assets/20260205_121719.webp",
    "/assets/20260205_121856.webp",
    "/assets/20251218_102342.webp",
    "/assets/resized_20200210_1349211.webp",
    "/assets/20220331_103109-1.webp",
    "/assets/20220330_112400-1.webp",
    "/assets/20220321_133823-1.webp",
    "/assets/20220404_143454.webp",
    "/assets/20220322_141502-1.webp",
    "/assets/20220321_133727-1.webp",
    "/assets/20220928_094930-1.webp",
    "/assets/20230914_131432.webp",
    "/assets/20230914_131120-1.webp",
    "/assets/nye-bislett-stadion.webp",
    "/assets/nye-bislett-stadion-1.webp",
    "/assets/dsc03081.webp",
  ],
  vegger: [
    "/assets/20230914_131110.webp",
    "/assets/20230914_131120.webp",
    "/assets/20251218_102342-1.webp",
    "/assets/20251218_103500.webp",
  ],
  broer: [
    "/assets/20250920_142833-edited.webp",
    "/assets/20250920_143210.webp",
    "/assets/20250920_143249.webp",
    "/assets/20250920_143254.webp",
    "/assets/tinnaa.webp",
    "/assets/dsc04433.webp",
    "/assets/dsc04702.webp",
    "/assets/tinnaa-1.webp",
  ],
  trapper: [
    "/assets/20241024_161200.webp",
    "/assets/20241024_161317.webp",
    "/assets/fin-trapp.webp",
    "/assets/20251104_132009-edited.webp",
    "/assets/trapp-over-1.webp",
    "/assets/trapp-under-5.webp",
    "/assets/019.webp",
    "/assets/025.webp",
    "/assets/034.webp",
    "/assets/031.webp",
    "/assets/20250110_085123.webp",
    "/assets/20250110_085038.webp",
    "/assets/trapp.webp",
  ],
};

export const fiskumSeedDocuments = [
  {
    _id: "settings",
    _type: "settings",
    label: "Globale innstillinger",
    companyName: "Fiskum Plate og Sveiseverksted AS",
    siteTitle: "Fiskum Plate og Sveiseverksted AS",
    siteDescription: "Over 60 år med solid kompetanse i stål og metall.",
    logo: { _type: "image", assetPath: "/assets/logo-7.png", alt: "Fiskum Plate og Sveiseverksted AS" },
    phone: "32 75 06 77",
    contactEmail: "post@fiskum-sveis.no",
    address: { street: "Kongsbergveien 791", postalCode: "3322", city: "Fiskum", country: "Norge" },
    socialLinks: { facebook: "https://www.facebook.com/fiskumsveis" },
  },
  {
    _id: "navbar",
    _type: "navbar",
    label: "Header og hovedmeny",
    columns: [
      link("Om oss", "page-om-oss"),
      link("Tjenester", "page-tjenester"),
      link("Kranutleie", "page-kranutleie"),
      link("Verksted", "page-verksted"),
      link("Referanser", "page-referanser"),
      link("Aktuelt", "page-aktuelt"),
      link("Kontakt oss", "page-kontakt-oss"),
    ],
  },
  {
    _id: "footer",
    _type: "footer",
    label: "Footer",
    subtitle: "Pålitelig, erfaren og profesjonell partner innen stål og metallarbeid.",
    columns: [],
  },
  {
    _id: "homePage",
    _type: "homePage",
    title: "Over 60 år med solid kompetanse i stål og metall",
    description: "Vi bygger stålbygg · etablert 1959",
    heroLead: "Fiskum Plate & Sveiseverksted AS leverer komplette løsninger innen stålkonstruksjoner, metallarbeider og bygg.",
    slug: slug("/"),
    heroImages: gallery(["/assets/hero-stadion.webp", "/assets/hero-stalbygg.webp", "/assets/hero-brobygg.webp"], "Prosjekt fra Fiskum Plate og Sveiseverksted"),
    pageBuilder: [
      {
        _key: key("intro"),
        _type: "cta",
        eyebrow: "Hva vi tilbyr",
        title: "Erfaren og pålitelig samarbeidspartner for stålbygg og metallarbeid.",
        richText: [block("Med mer enn seks tiår i bransjen tar vi hånd om hele prosessen fra første forespørsel til ferdig bygg. Vi leverer alt fra stålplatetak og sandwich-vegger til trapper, rekkverk, aluminium- og rustfrie løsninger.")],
      },
      {
        _key: key("process"),
        _type: "featureCardsIcon",
        eyebrow: "Hvordan det virker",
        title: "Vi følger velprøvde prosesser og leverer solide resultater.",
        cards: [
          { _key: key("card"), _type: "featureCardIcon", title: "Din forespørsel", richText: [block("Du deler behovene dine med oss, enten det gjelder stålbygg, trapper, rekkverk eller andre stålarbeider.")] },
          { _key: key("card"), _type: "featureCardIcon", title: "Befaring og rådgivning", richText: [block("Vi avtaler befaring på byggeplass eller verksted, vurderer løsningen og gir faglige råd.")] },
          { _key: key("card"), _type: "featureCardIcon", title: "Tilbud og planlegging", richText: [block("Du mottar et detaljert tilbud. Vi legger en plan for produksjon og montering som sikrer kvalitet og effektiv fremdrift.")] },
          { _key: key("card"), _type: "featureCardIcon", title: "Produksjon og levering", richText: [block("Vi produserer og monterer stålkonstruksjonene etter avtale, og leverer et komplett resultat klart til bruk.")] },
        ],
      },
      {
        _key: key("why"),
        _type: "cta",
        eyebrow: "Hvorfor velge oss",
        title: "Pålitelig, erfaren og profesjonell partner innen stål og metallarbeid.",
        richText: [block("Med over 60 års erfaring kombinerer vi tradisjonelt håndverk med moderne løsninger. Målet er trygge og varige konstruksjoner som er tilpasset kundens behov.")],
      },
      {
        _key: key("contact"),
        _type: "cta",
        eyebrow: "Kontakt oss i dag",
        title: "Be om et uforpliktende tilbud",
        richText: [block("Vi hjelper deg med alt fra prosjektering til ferdig bygg. Våre eksperter står klare til å levere kvalitetsløsninger innen stål, aluminium og rustfritt.")],
        buttons: [button("Send forespørsel", "page-kontakt-oss")],
      },
    ],
  },
  {
    _id: "page-om-oss",
    _type: "page",
    title: "Om oss",
    description: "Over 60 år med erfaring innen stål, metallarbeid og solide konstruksjoner.",
    slug: slug("/om-oss"),
    pageBuilder: [{ _key: key("content"), _type: "cta", richText: [block("Fiskum Plate og Sveiseverksted AS er en erfaren samarbeidspartner for kunder som trenger solide løsninger innen stålbygg, metallarbeider, trapper, rekkverk og konstruksjoner."), block("Vi kombinerer tradisjonelt håndverk med moderne metoder og følger prosjektene fra første forespørsel til ferdig leveranse.")] }],
  },
  {
    _id: "page-tjenester",
    _type: "page",
    title: "Tjenester",
    description: "Komplette løsninger innen stålbygg, fasade, tak, broer, trapper og rekkverk.",
    slug: slug("/tjenester"),
    pageBuilder: [{ _key: key("content"), _type: "cta", richText: [block("Vi leverer robuste og tilpassede løsninger for entreprenører, næringsliv og private kunder. Arbeidet kan omfatte alt fra produksjon på verksted til montering ute på byggeplass."), block("Hver leveranse planlegges med vekt på kvalitet, fremdrift og praktiske løsninger som tåler bruk over tid.")] }],
  },
  {
    _id: "page-verksted",
    _type: "page",
    title: "Verksted",
    description: "Eget verksted for produksjon, tilpasning og bearbeiding av metall og stålkonstruksjoner.",
    slug: slug("/verksted"),
    pageBuilder: [{ _key: key("content"), _type: "cta", richText: [block("Verkstedet vårt gjør det mulig å produsere, bearbeide og tilpasse løsninger etter prosjektets behov. Vi tar hånd om detaljer som er avgjørende for presis montering og lang levetid."), block("Vi jobber med stål, aluminium og rustfritt, og leverer både større konstruksjoner og mindre spesialarbeider.")] }],
  },
  {
    _id: "page-kranutleie",
    _type: "page",
    title: "Kranutleie",
    description: "Kranbil, transportkapasitet og praktisk bistand til løfteoppdrag.",
    slug: slug("/kranutleie"),
    pageBuilder: [{ _key: key("content"), _type: "cta", richText: [block("Vi tilbyr utleie av kranbil og bistand til transport- og løfteoppdrag for kunder som trenger trygg planlegging, riktig utstyr og fleksibel gjennomføring."), block("Kran- og transportvirksomheten er videreført som FPS Kranservice AS. Ta kontakt for kapasitet, tilgjengelighet og praktisk avklaring.")] }],
    image: { _type: "image", assetPath: "/assets/news-kranbil.webp", alt: "Kranutleie" },
  },
  {
    _id: "page-referanser",
    _type: "page",
    title: "Referanser",
    description: "Utvalgte prosjekter innen stål, metallarbeid, kran, transport og konstruksjoner.",
    slug: slug("/referanser"),
    pageBuilder: [{ _key: key("content"), _type: "cta", richText: [block("Her finner du referanser fordelt på fagområdene fra den gamle siden. Hver referanse har egen detaljside med galleri.")] }],
  },
  {
    _id: "page-aktuelt",
    _type: "page",
    title: "Aktuelt",
    description: "Siste nyheter og oppdateringer fra Fiskum Plate og Sveiseverksted AS.",
    slug: slug("/aktuelt"),
    pageBuilder: [{ _key: key("content"), _type: "cta", richText: [block("Her samles nyheter og oppdateringer fra virksomheten. Klikk deg videre for full visning av hver sak.")] }],
  },
  {
    _id: "page-kontakt-oss",
    _type: "page",
    title: "Kontakt oss",
    description: "Ta kontakt for befaring, tilbud eller spørsmål om stål- og metallarbeid.",
    slug: slug("/kontakt-oss"),
    pageBuilder: [{ _key: key("content"), _type: "cta", richText: [block("Har du spørsmål, er du alltid velkommen til å ta kontakt med oss. Vi avtaler gjerne befaring og gir råd om løsningen som passer best for prosjektet."), block("Telefon: 32 75 06 77"), block("E-post: post@fiskum-sveis.no"), block("Adresse: Kongsbergveien 791, 3322 Fiskum, Norge")] }],
  },
  {
    _id: "service-stalbygg",
    _type: "service",
    internalTitle: "Stålbygg",
    title: "Stålbygg",
    slug: slug("/stalbygg"),
    summary: "Komplette bærekonstruksjoner og stålbygg tilpasset prosjektets krav.",
    body: [block("Vi leverer komplette stålbygg - fra planlegging og prosjektering til produksjon og montering. Med over 60 års erfaring i bransjen har vi opparbeidet oss solid kompetanse og kan ta ansvar for hele prosessen, enten det gjelder næringsbygg, landbruksbygg eller andre konstruksjoner i stål."), block("Vårt mål er å skape bygg som kombinerer funksjonalitet, styrke og fleksibilitet. Vi sørger for at alt blir levert etter gjeldende standarder og med løsninger som er tilpasset kundens behov.")],
    gallery: gallery(serviceGallery.stalbygg, "Stålbygg"),
  },
  {
    _id: "service-vegger",
    _type: "service",
    internalTitle: "Vegger, fasade og tak",
    title: "Vegger, fasade og tak",
    slug: slug("/vegger"),
    summary: "Stålplatetak, sandwich-vegger og robuste fasadeløsninger.",
    body: [block("Vi leverer og monterer stålplatetak og sandwichvegger som gir byggene et solid, moderne og varig uttrykk. Våre løsninger kombinerer styrke og funksjonalitet med et estetisk preg som passer både næringsbygg, industrilokaler og landbruksbygg."), block("Med vår erfaring og kompetanse sørger vi for en nøyaktig og effektiv montering, slik at resultatet blir både tett, energieffektivt og holdbart.")],
    gallery: gallery(serviceGallery.vegger, "Vegger, fasade og tak"),
  },
  {
    _id: "service-broer",
    _type: "service",
    internalTitle: "Broer",
    title: "Broer",
    slug: slug("/broer"),
    summary: "Produksjon og montering av solide bro- og stålkonstruksjoner.",
    body: [block("Vi produserer og monterer stålkonstruksjoner til broer med fokus på styrke, sikkerhet og varighet. Våre løsninger bygger på lang erfaring og solid fagkompetanse."), block("Gjennom hele prosessen - fra planlegging til ferdig montering - sikrer vi at prosjektet oppfyller gjeldende krav og standarder.")],
    gallery: gallery(serviceGallery.broer, "Broer"),
  },
  {
    _id: "service-trapper",
    _type: "service",
    internalTitle: "Trapper, rekkverk og ramper",
    title: "Trapper, rekkverk og ramper",
    slug: slug("/trapper"),
    summary: "Skreddersydde trapper, rekkverk og ramper i stål, aluminium og rustfritt.",
    body: [block("Vi leverer trapper, rekkverk og ramper i stål som kombinerer funksjonalitet, sikkerhet og design. Våre løsninger kan tilpasses både innvendig og utvendig bruk."), block("Med fokus på presisjon og kvalitet sørger vi for solide konstruksjoner som tåler daglig bruk og samtidig gir et stilrent uttrykk.")],
    gallery: gallery(serviceGallery.trapper, "Trapper, rekkverk og ramper"),
  },
  {
    _id: "reference-stalbygg",
    _type: "projectReference",
    internalTitle: "Stålbygg",
    title: "Stålbygg",
    slug: slug("stalkonstruksjoner-og-bygg"),
    category: "stalbygg",
    summary: "Referanser fra stålbygg, bærekonstruksjoner og komplette stålleveranser.",
    body: [block("Et utvalg prosjekter som viser bredden i arbeidet med stålbygg, bærekonstruksjoner og tilpassede detaljer.")],
    gallery: gallery(serviceGallery.stalbygg, "Stålbygg"),
  },
  {
    _id: "reference-vegger",
    _type: "projectReference",
    internalTitle: "Vegger, fasade og tak",
    title: "Vegger, fasade og tak",
    slug: slug("vegger-fasade-og-tak"),
    category: "vegger-fasade-og-tak",
    summary: "Referanser fra stålplatetak, sandwichvegger og fasadeløsninger.",
    body: [block("Et utvalg arbeider med stålplatetak, sandwichvegger og fasadeløsninger til bygg som krever holdbare, tette og praktiske løsninger.")],
    gallery: gallery(serviceGallery.vegger, "Vegger, fasade og tak"),
  },
  {
    _id: "reference-broer",
    _type: "projectReference",
    internalTitle: "Broer",
    title: "Broer",
    slug: slug("broer"),
    category: "broer",
    summary: "Referanser fra bro- og stålkonstruksjoner med krav til styrke og presisjon.",
    body: [block("Et utvalg broprosjekter og stålkonstruksjoner der styrke, sikkerhet, presisjon og dokumentasjon er avgjørende for resultatet.")],
    gallery: gallery(serviceGallery.broer, "Broer"),
  },
  {
    _id: "reference-trapper",
    _type: "projectReference",
    internalTitle: "Trapper, rekkverk og ramper",
    title: "Trapper, rekkverk og ramper",
    slug: slug("trapper-rekkverk-og-ramper"),
    category: "trapper-rekkverk-og-ramper",
    summary: "Referanser fra trapper, rekkverk og ramper i stål, aluminium og rustfritt.",
    body: [block("Et utvalg trapper, rekkverk og ramper for både innvendig og utvendig bruk, med løsninger tilpasset mål, sikkerhet og ønsket uttrykk.")],
    gallery: gallery(serviceGallery.trapper, "Trapper, rekkverk og ramper"),
  },
  {
    _id: "reference-kran-og-transport",
    _type: "projectReference",
    internalTitle: "Kran og transport",
    title: "Kran og transport",
    slug: slug("kran-og-transport"),
    category: "kran-og-transport",
    summary: "Kranbil og transportkapasitet for løfteoppdrag og praktisk logistikk.",
    body: [block("Kran- og transportarbeid krever trygg planlegging, riktig utstyr og god koordinering på plassen.")],
    gallery: gallery(["/assets/news-kranbil.webp", "/assets/hero-brobygg.webp"], "Kran og transport"),
  },
  {
    _id: "news-vi-soker-laerlinger",
    _type: "newsPost",
    internalTitle: "Vi søker lærlinger!",
    title: "Vi søker lærlinger!",
    slug: slug("vi-soker-laerlinger"),
    publishedAt: "2026-03-09T09:00:00.000Z",
    excerpt: "Fiskum Plate og Sveiseverksted søker lærlinger.",
    mainImage: image("/assets/sprak.webp", "Vi søker lærlinger"),
    body: [block("Vi søker lærlinger som ønsker praktisk erfaring og faglig utvikling innen stål, sveising og metallarbeid."), block("Ta kontakt dersom du ønsker å lære faget i et miljø med lang erfaring og varierte oppdrag.")],
  },
  {
    _id: "news-kranservice",
    _type: "newsPost",
    internalTitle: "Vi tilbyr nå utleie av kranbil",
    title: "Vi tilbyr nå utleie av kranbil",
    slug: slug("var-kran-transportvirksomhet-heter-na-fps-kranservice-as"),
    publishedAt: "2026-02-27T09:00:00.000Z",
    excerpt: "Kran- og transportvirksomheten er videreført som FPS Kranservice AS.",
    mainImage: image("/assets/news-kranbil.webp", "Kranbil fra Fiskum Plate og Sveiseverksted"),
    body: [block("Vår kran- og transportvirksomhet heter nå FPS Kranservice AS. Vi tilbyr utleie av kranbil og bistand til transport- og løfteoppdrag."), block("Ta kontakt for kapasitet, tilgjengelighet og praktisk avklaring.")],
  },
  {
    _id: "faq-private",
    _type: "faq",
    title: "Leverer dere kun til næringskunder, eller også privatpersoner?",
    richText: [block("Vi leverer hovedsakelig til næringsliv og entreprenører, men tar også på oss oppdrag for privatkunder når det gjelder trapper, rekkverk og mindre stålarbeider.")],
  },
  {
    _id: "faq-prosess",
    _type: "faq",
    title: "Hvordan foregår prosessen fra forespørsel til ferdig leveranse?",
    richText: [block("Etter at vi mottar din forespørsel avtaler vi befaring ved behov. Deretter får du et detaljert tilbud, og vi tar ansvar for produksjon og montering frem til ferdig resultat.")],
  },
  {
    _id: "faq-sertifisering",
    _type: "faq",
    title: "Har dere nødvendige godkjenninger og sertifiseringer?",
    richText: [block("Ja, vi er sertifisert av SINTEF for CE-merking av våre produkter, og alle leveranser oppfyller gjeldende krav og standarder.")],
  },
  {
    _id: "faq-tilpasning",
    _type: "faq",
    title: "Kan dere tilpasse løsninger til spesifikke behov og tegninger?",
    richText: [block("Absolutt. Vi skreddersyr konstruksjoner og metallarbeider etter kundens ønsker, og samarbeider tett med både arkitekter og entreprenører.")],
  },
  {
    _id: "faq-levering",
    _type: "faq",
    title: "Hvor leverer dere prosjekter?",
    richText: [block("Vi har base på Østlandet, men leverer oppdrag over store deler av landet. Ta kontakt, så finner vi en løsning også for ditt prosjekt.")],
  },
];
